[build]
  command = "npm run build"
  publish = "out"


[build.environment]
  NODE_VERSION = "18.17.0"  # ou la version de Node.js que vous utilisez

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200